### PR TITLE
Create analysis example for pollution data & run black

### PR DESCRIPTION
**Pull request by mar3021**

### CODE REVIEW

**Comment by anitagraser** [comment]
Looks good, thanks. Please try to change the speed calculation for the outlier filter to km/h instead of m/s and then we can merge this.

**Comment by anitagraser** [comment]
Black addresses #14

**Comment by anitagraser** [comment]
Does the comment belong here? 
image

**Comment by mar3021** [comment]
> Does the comment belong here? image

The code is partially based on the Medium article, although in that cell it has been changed quite a bit

**Comment by anitagraser** [comment]
Please add the source of the pollution data to https://github.com/movingpandas/movingpandas-examples/blob/main/data/README.md

**Comment by anitagraser** [comment]
And please zip the dataset to reduce its size. Pandas should be able to read from zip

**Pull request merged**
